apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: dbd295x1w-nodejs
  janus-idp.io/tekton: dbd295x1w-nodejs
  backstage.io/kubernetes-id: dbd295x1w-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: dbd295x1w-nodejs
resources:
- deployment.yaml
- route.yaml
- service.yaml
